### ISSUE TITLE
Division Operation

### ISSUE THREAD

**Issue by MohamedSalahApdElzaher** [MohamedSalahApdElzaher/Simple_Calculator#3]
Hi @youssefmagdy1 ,
Your task:

1. Add Division Operation
2. Handle Exception Such as " / by zero "
3. divide overflow

**Comment by youssefmagdy1** [comment]
done 
 /* some comments 
; divisoin opertion 
		; 1. division operation 32bit => 64bit by 32bit 
			;1.a) the 64bit number is saved in EDX and EAX , 32 bit any operand by the instruction 
			;1.b) will result quotinent 32bit in EAX and remainder in 32bit in EDX 
				;* the CDQ convert doubleword to quadword 
			;1.c) the reminder may takes two ways : A- round up B- convert to fractional number 
			; 		we will use round up 
		; 2. fix divide by zero 
		; 3. divide overflow => i think itis will not happend 
		; 4. signed divide => error will happend when divide -8/4 and if it 8/-4 will not happend 
		; 	it works fine when make sign extend cqd , why it works? 
*/
